### ISSUE TITLE
AU915 support

### ISSUE THREAD

**Issue by moonlight0551** [disk91/WioLoRaWANFieldTester#14]
Are there plans for AU915 support?

**Comment by disk91** [comment]
Sure, I'll soon add different new zones (the one supported by LoRa E5 chip)

**Comment by disk91** [comment]
AU915 support added

**Comment by moonlight0551** [comment]
Thanks Paul, much appreciated.

Sent from Yahoo Mail on Android 
 
  On Wed, 29 Sep. 2021 at 9:40 pm, Paul ***@***.***> wrote:   


AU915 support added

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by moonlight0551** [comment]
Hi Paul, just trying to set up my TTN credentials in the Wio and if I connect to it via a serial port, I cannot add the AU915 zone. If I type Z=EU868 I get ZONE: EU868 but if I try Z=AU915 I get a KO. AS923, US915, KR920, IN865 all work! Something not quite right?

Cheers David
    On Wednesday, 29 September 2021, 09:40:36 pm AEST, Paul Pinault ***@***.***> wrote:  
 
 


AU915 support added

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by disk91** [comment]
The binary is not updated with the last commit fixing this.
You setup EU868 as an exemple.
Then you click on 5D button and reset the device. after 1s you release the 5D button and access the IDs setup screen. You can select AU915 then.
The next binary will include the serial configuration fix.

**Comment by moonlight0551** [comment]
Hi Paul, tried that out and it all appears to work but no joy in connecting to the TTN. So I fired up my SDR and the only signals I see transmitted regardless of the zone setting (EU868, US915, AS923, KR920, IN865 or AU915) is on 868Mhz.  So it looks to be the default zone and regardless of what you change it to, it remains EU868.
    On Thursday, 30 September 2021, 09:07:36 pm AEST, Paul Pinault ***@***.***> wrote:  
 
 


The binary is not updated with the last commit fixing this.
You setup EU868 as an exemple.
Then you click on 5D button and reset the device. after 1s you release the 5D button and access the IDs setup screen. You can select AU915 then.
The next binary will include the serial configuration fix.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by disk91** [comment]
I confirm a mistake with AU915, it was setting IN865 instead of the right zone.
It will be fixed in the coming commit and binary update

**Comment by moonlight0551** [comment]
Thanks for your time. I reckon you should check them all as no matter which zone I select it still transmits on 868MHz when trying to join the TTN.
    On Friday, 1 October 2021, 05:35:59 pm AEST, Paul Pinault ***@***.***> wrote:  
 
 


I confirm a mistake with AU915, it was setting IN865 instead of the right zone.
It will be fixed in the coming commit and binary update

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
