### ISSUE TITLE
Add an option to access the E5 from the Serial port to pilot E5 from a computer

### ISSUE THREAD

**Issue by disk91** [disk91/WioLoRaWANFieldTester#17]

**Comment by hallard** [comment]
This could allow us to set up custom ID once and they will be retrieved by #18, and cherry on the cake, not stored in code and not erased bay FW update (of course available with AT command direct on E5) so not ultra secure proof

**Comment by disk91** [comment]
Pushed in commit 957c88fb17325bdbb3f9f892cf9e6a976a877ca5
