### ISSUE TITLE
    #error "You must change the SoftSerial Buffer size in SoftSerial.h for 128"

### ISSUE THREAD

**Issue by paddygoat** [disk91/WioLoRaWANFieldTester#27]
#error "You must change the SoftSerial Buffer size in SoftSerial.h for 128"

Bonjour! 
I am trying to compile using Arduino IDE and the first error is for the buffer value in SoftSerial.h, but after searching for this file, there is no file with this name on my machine and so I am unable to edit it.
Please, where is the file supposed to be located?
Merci beaucoup.

Full error message:
Arduino: 1.8.13 (Linux), Board: "Seeeduino Wio Terminal, Master, Enabled, 120 MHz (standard), Small (-Os) (standard), 50 MHz (standard), Arduino, Off, On"

gps.cpp:77:6: error: #error "You must change the SoftSerial Buffer size in SoftSerial.h for 128"
     #error "You must change the SoftSerial Buffer size in SoftSerial.h for 128"
      ^~~~~
gps.cpp:55:28: error: no matching function for call to 'Adafruit_GPS::Adafruit_GPS(SoftwareSerial*)'
 Adafruit_GPS GPS(&GPSSerial);
                            ^
In file included from sketch/gps.cpp:42:0:
/home/paddy/Arduino/libraries/Adafruit_GPS_Library/src/Adafruit_GPS.h:92:3: note: candidate: Adafruit_GPS::Adafruit_GPS()
   Adafruit_GPS(); // Constructor for no communications, just data storage
   ^~~~~~~~~~~~
/home/paddy/Arduino/libraries/Adafruit_GPS_Library/src/Adafruit_GPS.h:92:3: note:   candidate expects 0 arguments, 1 provided
/home/paddy/Arduino/libraries/Adafruit_GPS_Library/src/Adafruit_GPS.h:91:3: note: candidate: Adafruit_GPS::Adafruit_GPS(SPIClass*, int8_t)
   Adafruit_GPS(SPIClass *theSPI, int8_t cspin); // Constructor when using SPI
   ^~~~~~~~~~~~
/home/paddy/Arduino/libraries/Adafruit_GPS_Library/src/Adafruit_GPS.h:91:3: note:   candidate expects 2 arguments, 1 provided
/home/paddy/Arduino/libraries/Adafruit_GPS_Library/src/Adafruit_GPS.h:90:3: note: candidate: Adafruit_GPS::Adafruit_GPS(TwoWire*)
   Adafruit_GPS(TwoWire *theWire);    // Constructor when using I2C
   ^~~~~~~~~~~~
/home/paddy/Arduino/libraries/Adafruit_GPS_Library/src/Adafruit_GPS.h:90:3: note:   no known conversion for argument 1 from 'SoftwareSerial*' to 'TwoWire*'
/home/paddy/Arduino/libraries/Adafruit_GPS_Library/src/Adafruit_GPS.h:89:3: note: candidate: Adafruit_GPS::Adafruit_GPS(HardwareSerial*)
   Adafruit_GPS(HardwareSerial *ser); // Constructor when using HardwareSerial
   ^~~~~~~~~~~~
/home/paddy/Arduino/libraries/Adafruit_GPS_Library/src/Adafruit_GPS.h:89:3: note:   no known conversion for argument 1 from 'SoftwareSerial*' to 'HardwareSerial*'
/home/paddy/Arduino/libraries/Adafruit_GPS_Library/src/Adafruit_GPS.h:81:7: note: candidate: constexpr Adafruit_GPS::Adafruit_GPS(const Adafruit_GPS&)
 class Adafruit_GPS : public Print {
       ^~~~~~~~~~~~
/home/paddy/Arduino/libraries/Adafruit_GPS_Library/src/Adafruit_GPS.h:81:7: note:   no known conversion for argument 1 from 'SoftwareSerial*' to 'const Adafruit_GPS&'
In file included from sketch/testeur.cpp:23:0:
sketch/testeur.cpp: In function 'void initState()':
keys.h:28:16: error: 'EU868' was not declared in this scope
 #define __ZONE EU868
                ^
sketch/testeur.cpp:50:21: note: in expansion of macro '__ZONE'
     loraConf.zone = __ZONE;
                     ^~~~~~
Multiple libraries were found for "Adafruit_ZeroDMA.h"
 Used: /home/paddy/.arduino15/packages/Seeeduino/hardware/samd/1.8.2/libraries/Adafruit_ZeroDMA
 Not used: /home/paddy/Arduino/libraries/Adafruit_Zero_DMA_Library
exit status 1
#error "You must change the SoftSerial Buffer size in SoftSerial.h for 128"

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by disk91** [comment]
Please read and follow developper documentation:

https://github.com/disk91/WioLoRaWANFieldTester/blob/master/doc/DEVELOPMENT.md
