### ISSUE TITLE
 support for WIO Field Tester in AS923_4

### ISSUE THREAD

**Issue by tzacha** [disk91/WioLoRaWANFieldTester#33]
Hi 
i recently received my WIO Field tester, i configured it to AS923_4 
but it docent seem to connect to any Helium Miner although i got 3 miners installed all around my house 
i did manage to see some connectivity since when i watched for it on https://cargo.helium.com/  i noticed its signal
but on the device it self, i don't get any signal noticed in any of the screens , 
on the status area i get only "Lost" 

can it be issue of AS923_4 region , which isnt supported? , or do i have to configure something, on the device?
i even tryed upgrading to ver 1.6 ... 

thanks
Tzach

**Comment by disk91** [comment]
AS923_4 is supported.
If you see it on cargo, it works.
Lost is related to the Ack or network response. Some of the response are lost, particularly when the device is too close from an antenna. You can also have this when you are in SF10 with a limit of communication time on a single frequency (like in the US915). To make sure, give it a try with a SF9 or SF7.
