### ISSUE TITLE
Support for WIO Tester AS923_1 with TTN

### ISSUE THREAD

**Issue by simon-anderson** [disk91/WioLoRaWANFieldTester#37]
Hello,

I've tried everything to get a WIO tester working with TTN Australia without success, and I hope someone will be able to tell me where I've gone wrong.

The consistent error message is "MIC Mismatch"

The DevEUI and the AppEUI are correct. Is the field "SerialNumber" when the device connects over USB the AppKey? If not, how can the AppKEY be queried? It appears as just Xs on the configuration seen and I don't seem to be able to set it with a serial console application.

**Comment by disk91** [comment]
Are you using RFM95 or LoRa-E5 ?
