### ISSUE TITLE
Reset SEEED bundle

### ISSUE THREAD

**Issue by ZaineJJ** [disk91/WioLoRaWANFieldTester#38]
Hi is there a way to reset the seeed bundle?
I think I broke it.... Didn't know nothing should be done but I watched video and did the steps and Im getting black screen, then I troubleshoot and installed the GPS file to "reset" and i'm seeing
"Verifying setup" 
"Setup Ok, nothing to do" 

Please advise and appreciate all the help :D

**Comment by disk91** [comment]
You should read and follow issue #34
