### ISSUE TITLE
Busy Response to Zone Config

### ISSUE THREAD

**Issue by Hobietime** [disk91/WioLoRaWANFieldTester#40]
Hello. I bought the WiO terminal from seed preconfigured.

I accidentally chose the wrong region on first boot.

I tried to send Z=US915 after the device is on, but I only receive a response of "Busy" from the terminal.

Is there another way to change the zone after the terminal is configured?

**Comment by disk91** [comment]
Hello
Sure : during the boot you hold the 5directions button for a couple of seconds, then you release it and you will reach the setup screen to change this. 
Paul

_______________________________
Paul Pinault
http://www.disk91.com
http://www.twitter.com/disk_91

**Comment by Hobietime** [comment]
Thank you! That did the trick.

Caio
