### ISSUE TITLE
Does Discovery mode support TTN?

### ISSUE THREAD

**Issue by HAO156** [disk91/WioLoRaWANFieldTester#47]
**Does Discovery mode support TTN? Or does it only support Helium?** 
  When I use Discovery mode in the TTN environment.The link in the QR code cannot be accessed from a mobile phone or computer.
![image](https://user-images.githubusercontent.com/46951214/183599437-a1e76e81-d8c7-4b87-b0bd-a81225046be5.png)

  Any help would be appreciated.

**Comment by disk91** [comment]
Discovery mode is not yet implemented with TTN. 
It will be added soon. 

_______________________________
Paul Pinault
http://www.disk91.com
http://www.twitter.com/disk_91

**Comment by HAO156** [comment]
> Discovery mode is not yet implemented with TTN. It will be added soon.
> […](#)
> _______________________________ Paul Pinault http://www.disk91.com http://www.twitter.com/disk_91
> Le 9 août 2022 à 10:15, Michael.Hao ***@***.***> a écrit : ﻿ Does Discovery mode support TTN? Or does it only support Helium? When I use Discovery mode in the TTN environment.The link in the QR code cannot be accessed from a mobile phone or computer. Any help would be appreciated. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

**Comment by HAO156** [comment]
Thank you for the reply. Looking forward to supporting the discovery mode of the TTN version.
