### ISSUE TITLE
Discovery mode results deleting

### ISSUE THREAD

**Issue by Chris-S44** [disk91/WioLoRaWANFieldTester#48]
Would it be possible to have an option to immediately delete discovery mode results and not to wait the 2hrs?
It would be nice to have for testing 2 different antennas back to back.

**Comment by disk91** [comment]
There is currently no option for doing this.
This is a good feature request, I'll add this for the next updates

**Comment by Chris-S44** [comment]
Thanks Paul. That will be great.
