### ISSUE TITLE
In Bootloader Mode

### ISSUE THREAD

**Issue by Meyblaubaer** [disk91/WioLoRaWANFieldTester#52]
Hello,

i got the Seeed Package. After Updating to newest Firmware, The Device keeps booting in bootloader mode. I tried reinstalling firmware without success.

**Comment by disk91** [comment]
That is strange and unusual. What firmware file did you flashed ?

_______________________________
Paul Pinault
http://www.disk91.com
http://www.twitter.com/disk_91

**Comment by Meyblaubaer** [comment]
I was able to resolve the failure. It was because an faulty USB-C Cable, something went wrong. After uploading the Arduino "Blink Example" i was able to reupload with v1.3 and after this to the actual firmware. So i think it was a fault on my side, and this issue can be closed.
