### ISSUE TITLE
Are TTN credentials lost when going off battery?

### ISSUE THREAD

**Issue by ffries** [disk91/WioLoRaWANFieldTester#73]
Dear Disk91,

But what happens if battery goes off completely to 0%? All all TTN credentials lost and reverted to stock firmware? This is not a problem for Helium as credentials are hard-coded. But this is surely a problem for TTN. Is there a workaround other than clearing eprom? Do we need to recompile firmware?

All this is not very clear in a documentation, please make a clarification for newbies like me.

Kind regards,
Ffries

**Comment by disk91** [comment]
No they are not, credentials are stored in NVM and LoRa-E5 EEPROM

**Comment by ffries** [comment]
Thanks, closing the issue.

**Comment by ffries** [comment]
I understand what is going on : credentials are locked. I tried to remove the lock and use the lastest firmware. It reboots but credentials are still locked.

There should be a way to store credentials from the UI or using AT commands.

**Comment by ffries** [comment]
Dear Disk91,

Thank you for your answer. I am testing TTN coverage and I could connect to TTN using AT commands. This worked well. However, when switching-off WioLoRaWANFieldTester credentials are back to Helium.

Kind regards,
FFries

**Comment by disk91** [comment]
Hello, sorry to answer so late, I missed your response.
You can follow the guide in documentation to unlock your device and definitly remove the seeed factory configuration.

**Comment by disk91** [comment]
see: https://github.com/disk91/WioLoRaWANFieldTester/issues/34
